[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

# Optional: redirect all requests to index.html (useful for SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200